### ISSUE TITLE
Select box issue ibn IE11

### ISSUE THREAD

**Issue by umbundu** [taniarascia/primitive#3]
Tania,
How are you? I am really happy to evaluate your framework: it looks really clean and light. I noticed that the select boxes display a little tick next to the drop down arrow if you use IE11.
Any idfeas?
Thanks,
Everardo
ps. I could send you a picture.

Also, would you mind if I try to add the following components to your framnework?
tabs, accordions, modals, and date and time pickers.

**Comment by taniarascia** [comment]
You're right, it does have that issue in IE11. Since there are no more conditional statements for IE 10 and 11, all I've seen is this code hack:

```css
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    // IE10+ CSS here
}
```

Do you have any ideas?

At this time, I'm not interested in adding tabs/accordions/modals to the framework, as most sites I make don't use them, and I'd rather use as little bloat as possible.
